"""honest-persist - schema-first, pure-function persistence.

Schema as data, migrations as a pure diff, queries as data. I/O only at the boundary.
"""

from honest_persist.abstractions import (
    array_append,
    array_reindex,
    array_remove,
    array_set,
    closure_ancestors,
    closure_delete,
    closure_descendants,
    closure_insert,
    closure_move,
    enum_seed_queries,
    expand_schema,
    map_put,
    map_remove,
    range_adjacent,
    range_contains,
    range_overlaps,
)
from honest_persist.apply import apply, reconstruction_sql, requires_reconstruction, to_sql
from honest_persist.connect import connect_with_retry, open_pool
from honest_persist.cutover import (
    bulk_copy_table,
    copy_batch_query,
    cutover_advance,
    cutover_phases,
    cutover_plan,
    cutover_read_target,
    mirror_write,
)
from honest_persist.migrate import inspect, migrate
from honest_persist.check import check_holds, dialect_enforces_check, enforce_checks, parse_check, table_checks, validate_checks
from honest_persist.execute import execute, execute_many, execute_one, execute_scalar
from honest_persist.instrumented import emit_pool_event, instrumented_execute
from honest_persist.pool import (
    POOL_LIFECYCLES,
    acquire_connection,
    close_pool,
    empty_pool_registry,
    get_pool,
    is_idle,
    lease_connection,
    new_pool,
    reap_idle,
    recreate_ephemeral,
    release_connection,
    resolve_pool_key,
    should_retry,
)
from honest_persist.queue import (
    backoff_delay,
    drain_queue,
    empty_write_queue,
    enqueue_write,
    is_stalled,
    merge_pending,
    queue_from_jsonl,
    queue_to_jsonl,
)
from honest_persist.supervisor import enqueue_durable, load_queue, run_drain_loop, save_queue, supervise_drain
from honest_persist.query import (
    checked_delete,
    checked_insert,
    checked_select,
    checked_update,
    delete,
    insert,
    raw,
    select,
    update,
)
from honest_persist.transaction import transaction
from honest_persist.schema import diff, object_registry_queries, refresh_materialized_view, validate_schema
from honest_persist.instrument import (
    POOL_FAULT_CODES,
    build_migration_event,
    build_pool_event,
    build_query_event,
    build_transaction_event,
    extract_table,
    pool_fault,
    sql_hash,
)
from honest_persist.types import (
    Ambiguity,
    Column,
    Constraint,
    DiffResult,
    Index,
    Operation,
    Query,
    Table,
    diff_result,
    operation,
)

__all__ = [
    "diff",
    "validate_schema",
    "apply",
    "to_sql",
    "requires_reconstruction",
    "reconstruction_sql",
    "parse_check",
    "check_holds",
    "dialect_enforces_check",
    "table_checks",
    "enforce_checks",
    "validate_checks",
    "select",
    "insert",
    "update",
    "delete",
    "raw",
    "checked_select",
    "checked_insert",
    "checked_update",
    "checked_delete",
    "execute",
    "execute_one",
    "execute_scalar",
    "execute_many",
    "transaction",
    "operation",
    "diff_result",
    "Column",
    "Index",
    "Constraint",
    "Table",
    "Operation",
    "Query",
    "Ambiguity",
    "DiffResult",
    "POOL_FAULT_CODES",
    "pool_fault",
    "extract_table",
    "sql_hash",
    "build_query_event",
    "build_migration_event",
    "build_pool_event",
    "build_transaction_event",
    "instrumented_execute",
    "emit_pool_event",
    "POOL_LIFECYCLES",
    "resolve_pool_key",
    "empty_pool_registry",
    "get_pool",
    "is_idle",
    "reap_idle",
    "recreate_ephemeral",
    "new_pool",
    "acquire_connection",
    "release_connection",
    "lease_connection",
    "open_pool",
    "close_pool",
    "should_retry",
    "connect_with_retry",
    "inspect",
    "migrate",
    "cutover_phases",
    "cutover_advance",
    "cutover_read_target",
    "cutover_plan",
    "copy_batch_query",
    "bulk_copy_table",
    "mirror_write",
    "expand_schema",
    "range_overlaps",
    "range_contains",
    "range_adjacent",
    "array_append",
    "array_set",
    "array_remove",
    "array_reindex",
    "map_put",
    "map_remove",
    "closure_insert",
    "closure_descendants",
    "closure_ancestors",
    "closure_delete",
    "closure_move",
    "enum_seed_queries",
    "object_registry_queries",
    "refresh_materialized_view",
    "empty_write_queue",
    "enqueue_write",
    "merge_pending",
    "drain_queue",
    "queue_to_jsonl",
    "queue_from_jsonl",
    "backoff_delay",
    "is_stalled",
    "save_queue",
    "load_queue",
    "supervise_drain",
    "enqueue_durable",
    "run_drain_loop",
]
