"""BDD step scaffolding (section 8.2): generate a chain's gherkin step registry from its declarations.

honest-test connects developer-authored .feature files to chain links through step scaffolding it
generates from the chain — a given step that classifies the captured slot values into a manifest, a when
step that runs the chain, and then steps that assert the result is ok or carries a fault code. The
handlers conform to honest-gherkin's step contract: pure functions that take the immutable context plus
bound captures and return a NEW context, wired through register(registry) -> registry, never via
decorators or a mutable shared context. The step patterns are generated by a fixed convention so a
developer can write .feature steps against them: the when/then wording follows the chain name, and the
given step captures one value per manifest slot.
"""

from honest_gherkin import empty_registry, register_step
from honest_type import classify, execute_chain


def _humanize(name):
    """A chain or slot name as spoken words: underscores become spaces (create_user -> create user)."""
    return name.replace("_", " ")


def _given_pattern(name, slots):
    """The given-step pattern for a chain: a manifest for it, capturing one value per slot."""
    fields = " and ".join(f'{slot} "{{{slot}}}"' for slot in slots)
    return f"a manifest for {_humanize(name)} with {fields}"


def scaffold_chain(name, links, vocab, binding, slots):
    """Generate the honest-gherkin step registry for a chain (section 8.2): the given step classifies the
    captured slot values into a manifest, the when step runs the chain, and the then steps assert the
    result is ok or carries a fault code. Every handler is a pure returns-new-context wired through
    register_step — no decorators, no mutable shared context. Returns a populated registry."""
    def given(context, **captures):
        return {**context, "manifest": classify([captures[slot] for slot in slots], vocab, binding)}

    def when(context):
        return {**context, "result": execute_chain(links, context["manifest"])}

    def then_ok(context):
        assert "ok" in context["result"]
        return context

    def then_fault(context, code):
        assert "err" in context["result"]
        assert context["result"]["err"]["code"] == code
        return context

    registry = empty_registry()
    registry = register_step(registry, "given", _given_pattern(name, slots), given)
    registry = register_step(registry, "when", f"the {_humanize(name)} runs", when)
    registry = register_step(registry, "then", "the result is ok", then_ok)
    registry = register_step(registry, "then", 'the result has a fault code "{code}"', then_fault)
    return registry
